apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: kube-system
  # If you're using Amazon EKS with IAM Roles for Service Accounts, specify the following annotation.
  # Otherwise, you may safely omit it.
  annotations:
    # Substitute your account ID and IAM service role name below.  
    #eks.amazonaws.com/role-arn: arn:aws:iam::150625325991:role/eks-to-route53
    eks.amazonaws.com/role-arn: {{ .Values.eksToRoute53rolearn }}