{{- $fullName := include "scraper-generic-service.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
type: Opaque
data:
  {{- range $key, $val := .Values.env.secret }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end}}